### ISSUE TITLE
Configure Binder separately for `stable` and `latest` documentation

### ISSUE THREAD

**Issue by HTenkanen** [r5py/r5py#122]
Okay, seems to work as well configuring this similarly in conf.py. Hence, the workflow would be such that for each **release** (which goes in RTD under the `stable` version) we should do following:

1. Update the Binder launch button in repo Readme.md to point to the **tagged/released** version (e.g. `v0.3.3`).
2. Update the `"repository_branch"` in `html_theme_options` in `conf.py` to point to the tagged/released version (e.g. `v0.3.3`).

After these steps, those should be replaced with the original ones to get the `latest` version in RTD to work correctly with the latest r5py codebase from `main`.

_Originally posted by @HTenkanen in https://github.com/r5py/r5py/pull/118#discussion_r879316335_

**Comment by christophfink** [comment]
I’m thinking of when in the toolchain to make these changes. The problem is that it should be part of the commit that is tagged with v0.0.0. So it should be in the very beginning of https://github.com/r5py/r5py/blob/main/.github/workflows/release-and-deploy-v-tags.yml, but then history needs to be rewritten/the tag deleted and created again for the newly added commit (but then we should not run this another time)

**Comment by christophfink** [comment]
Maybe we could, instead, have a branch `stable` into which we always merge `main` when running `release-and-deploy-v-tags.yml`

**Comment by christophfink** [comment]
so, rather than having release/tag specific versions, have one stable branch that is always pointing to the latest release version

**Comment by christophfink** [comment]
https://docs.readthedocs.io/en/stable/builds.html#default-environment-variables

**Comment by HTenkanen** [comment]
Resolved in #124
