### ISSUE TITLE
Travel times are non-replicable

### ISSUE THREAD

**Issue by dtreich-itdp** [r5py/r5py#240]
**Describe the bug**
Given the same input data (origins/destinations, OSM, and GTFS), and the same parameters, r5py will return travel-time matrices with very significant differences. This seems to happen whether or not I rebuild the network or regenerate the computer in between runs. Most O/D pairs are the same, but a small fraction of pairs are substantially different - off by 20% or more of the travel time, often tens of minutes, enough to raise serious doubts concerning the quality of the results. 

I'm not an expert, it's very likely that I've made some mistake in configuring my inputs or my parameters, but I've been digging through the r5py documentation and trying everything I can think of, and I can't get r5py to give replicable results. Help me find what I'm doing wrong?

**To Reproduce**
0. I've tested both the development version of r5py and the stable release, they seem to have the same issue.
1. Use this [Google Drive](https://drive.google.com/drive/folders/1RsCRm7ejjTZ9kshMO7sg3_G5qbhwBFsh?usp=sharing) to download the data (scenarios/existing_conditions/) and the script (routing.py) that I'm using to generate travel_time matrices.
2. Run routing.route_scenario('scenarios/existing_conditions/'), and move the resulting files out of the results/ directory.
3. Run routing.route_scenario('scenarios/existing_conditions/') again, and compare the results to the first run. 

**Expected behavior**
For my intended use in transportation planning, I need a routing engine that can be configured to return identical, deterministic results every time an analysis is run on the same input data with the same parameters.

**Environment:**

    OS: Ubuntu 20.04.4 LTS
    Python package source: conda
    Versions of Python, Java Development Kit, Python modules
    Python 3.9
    javac 11.0.16 (I think, from javac -version, I'm not certain how to check within conda/python)

**Comment by christophfink** [comment]
Hi!

Yes, we are aware of a certain non-deterministic component in the routes. It seems to be a design choice of the underlying R5 engine (https://github.com/conveyal/r5), and we currently have not decided whether we want to try to handle this any different. 

In our test data sets, we found that, often, it is the access or egress from an origin point or to a destination point that is causing the most random contribution to travel time. If you want to eliminate this, snap the origin and destination to the closest point on the street network. We are working on a helper function to achieve exactly this, but it’s still taking a bit.

**Comment by christophfink** [comment]
see also: https://github.com/r5py/r5py/issues/224

**Comment by ethan-moss** [comment]
Hi,

I have also been experiencing travel times that are non-replicable. This is with both the [Helsinki demo data](https://github.com/r5py/r5py/tree/main/docs/data/Helsinki) and an alternative .pbf/GTFS source I have been using with OTP that gives deterministic results there. I notice from the Conway, Byrd and van de Linden 2017 paper there is a non-deterministic/Monte Carlo aspect to r5's routing algo when the GTFS/transit data is frequency-based.  The Helsinki GTFS data does have a `frequencies.txt` file, but since this file is optional in the GTFS spec I have re-run with this file removed and the results remain non-deterministic. The other GTFS data source I have been using is time-table based (has no frequencies.txt file) and gives non-deterministic results too.

To explore the 'snapping' , as a pre-processing step I extracted the node coordinates from the OSM file using `osmium` and I have snapped my origin/destination points to the closest OSM node and then re-run. The results were also non-deterministic in this case.

I have also tried various combinations of transit modes/walking, building the network with and without GTFS data, but I'm not yet able to get repeatable results. Any help/advice would be greatly appreciated, and if I can assist with anything just let me know.

Environment:
- OS: macOS Monterey v12.6
- Python package source: pypi/pip
- Python version: 3.9.16
- Java: AdoptOpenJDK 11.0.11+9

**Comment by christophfink** [comment]
b98edd8 adds a test to ensure the behaviour is deterministic. This means, this should be resolved in PR #258

**Comment by christophfink** [comment]
Reopening this issue, as I had to readjust the tests to allow up to four minutes of tolerance in-between subsequent runs, which does not sounds like it’s deterministic, at all. See PR #268

**Comment by christophfink** [comment]
Note to selves: It seems setting `RegionalTask.monteCarloDraws` to anything but 0 causes some randomness taking place even if no frequency-based transit feeds are used
