### ISSUE TITLE
Make travel time column names consistent betwen `TravelTimeMatrixComputer` and `DetailedItinerariesComputer`

### ISSUE THREAD

**Issue by wklumpen** [r5py/r5py#288]
Currently, `DetailedItinerariesComputer` returns the total travel time column as `total_time`, while `TravelTimeMatrixComputer` uses travel time. For consistency these should match.

**Comment by wklumpen** [comment]
Probably worth cross-referencing #278, #280, and #281

**Comment by christophfink** [comment]
Yes, I’ve already rewritten half of the `DetailedItinerariesComputer` to address #278 , part of that is to deliver results in a similar fashion to r5r’s equivalent: multiple rows per O/D-pair, grouped into ‘options’ (different trips that fulfil the routing parameters) and ’segments’ (parts of each trip, split by mode of transport or public transport route, typically). 

Contrarily to r5r’s implementation, I’ve gone ahead and now report only each segment’s travel time, which, consequently, is named `travel_time`. I’ll include a short example in the documentation as how to use a simple `groupby()` to extract the travel time per option, or the minimum/mean travel time per O/D-pair

It’s all in the making, but tests are still untouched, which is why I haven’t opened a PR, yet. You can see the current changes in https://github.com/christophfink/r5py/tree/278-keep-geometry

**Comment by christophfink** [comment]
Actually have to add a correction to my previous statement: the name `total_time` is, in its current implementation, correct, as it includes `wait_time` and `travel_time`. Since this `total_time` is redundant information (simply the sum of the two), I feel it would be misleading to create such a column. I’ll put in extra effort in the documentation to ensure the users are aware of this

**Comment by wklumpen** [comment]
Sounds good. I mainly would suggest that `travel_time` as reported in the standard matrix computer match the meaning and values of the `travel_time` column in the detail computer - or if the column doesn't exist we can document how to calculate it.
