### ISSUE TITLE
LegMode.CAR takes very long to run on regional level

### ISSUE THREAD

**Issue by sruinaard** [r5py/r5py#358]
For a study with many origins and many destinations in Västra Götaland, Sweden, it is very well possible to obtain travel time matrices for transit, walking and cycling (apart and combined). When changing the transport mode to the car only (travel_time_matrix_computer with transport_modes = [LegMode.CAR]), the calculations take forever (if not, endless, as running overnight was not enough). 

At least the following three aspects are contributing to slowing down the algorithm:
1. We are interested in a large number of origins (~2300) and destinations (~2800);
2. The locations are in some cases far apart (up to ~25km Euclidean distance), as the study is regional;
3. Every road link has a designated speed instead of using an average speed as for walking and biking. 

We hoped to get a travel time matrix for the car as well, as it is an interesting benchmark to compare to the other transport modes. Do you deem it possible with the given inputs, or have tips on how to improve computing time? (And could max_time_driving and access_modes contribute to lowering computing time?)

**Comment by christophfink** [comment]
Hi!

Thanks for reporting this issue. I’ve been wondering how to best reply, as I’m not sure what kind of reasons might be behind the problems you’re seeing.

We are running a fairly large, regional analysis ourselves (https://github.com/DigitalGeographyLab/Helsinki-Travel-Time-Matrices/), in which we also assign car speeds directly to the edges. While we do use large virtual machines (64 cores, 100GiB RAM + plenty of swap), that’s mostly because we have around 13000² origins and destinations (close to 200 mio vs your 6.5 mio O/D-pairs)

Note that R5 has been developed from a public transport perspective, so it is to be expected that street routing is performing somewhat more poorly, but it should not be by orders of magnitude

With your study area being located in Sweden, I would assume the OpenStreetMap network is in good enough state (which is something that could have an influence that’s particular to certain transport modes)

Could you maybe share (some of) your input data? 
(if you want to share them confidentially, send me an email: christoph.fink@helsinki.fi )

**Comment by sruinaard** [comment]
Hi Christoph, thank you for your reaction!

Good news, by updating R5py (I first installed it a month ago, and updated it yesterday), setting snap to network 500m, and the max_time on 30 minutes, I did not experience this issue anymore. It was very quick actually!

**Comment by christophfink** [comment]
Fantastic to hear that it works now!
