### ISSUE TITLE
Add a shorthand to load all files in a directory into a TransportNetwork

### ISSUE THREAD

**Issue by christophfink** [r5py/r5py#36]
> 3\. Building the network
>         I believe `TransportNetwork()` and `setup_r5()` would be the equivalent function used to create a network, right?
> 
> 
>     * r5py: `network = TransportNetwork(osm_pbf=osm_pbf, gtfs=gtfs)`
> 
>     * r5r: `network =  setup_r5( data_path = "local_dir")`
> 
> 
> I see that users would need to pass the the addresses of a `osm.pbf` and `gtfs.zip` files to `TransportNetwork()`. I find this behavior a bit strange. How does it work when users have two or more GTFS feeds from different agencies. We know R5 automatically detects and takes in one `osm.pbf` and all the `gtfs.zip` files in the path. This one of the reasons we require `r5r` users to input the address of the local directory where the data is stored. Perhaps we should have a separate issue to discuss the workflow we would expect from users and the expected behavior of these download and build network functions.

This is splitting up issue #25 into smaller pieces (re: https://github.com/r5py/r5py/issues/25#issuecomment-1122901350 )

**Comment by christophfink** [comment]
Honestly, this is something that low-key bothered me about r5r. We actually want specific files, not ’everything I have’. Many people like to keep all their data somewhere in a common place (thinking about historical gtfs or network data, for instance), and not in a project-specific directory.

On a side note, `gtfs` is a list of files (can be zero or more).

I could imagine building a wrapper around it, which searches for all possible GTFS files and the first (?) `.osm.pbf` to hand to the TransportNetwork constructor.

**Comment by HTenkanen** [comment]
Yeah, I think the convention that is used by r5r is originating how also OpenTripPlanner works, i.e. probably follows the conventions of r5. I do agree that the logic is not perhaps the best one (at least when working with OTP, you tend to create multiple copies of the same files because of this). Being able to list specific GTFS feeds with a list would be more specific and it would allow you to have as many GTFS feeds in your directory as you want, but still you could control which of them are used. And as @christophfink mentions, it's easy to build a wrapper that searches all the feed zip files and uses them if needed. 

But again, this is a question of how much do we want to follow the original implementations and how they work (OTP + r5 + r5r). For someone, who has used these tools before (OTP, r5, r5r), the original logic might be easier to grasp, but for new users having more control might be a good feature.

**Comment by HTenkanen** [comment]
Yep, my vote goes to have a method for doing this. 

Any thoughts @rafapereirabr, @wklumpen?

**Comment by rafapereirabr** [comment]
I totally understand why it is a good practice to point to specific files, indestad of all files in a directory. I like keeping consistency across packagesm I'm not strongly opposed to this difference if this is something that is compatible with R5 . There is one important thing to keep in mind, though.

I have the impression that R5 was designed to expect a directory address as an input (not separate osm and gtfs files) at least in part because R5 uses that path to save the network data (the 3 files below) once the network is built. I would be great to have @mattwigway's or @mvpsaraiva's thoughts on this.

- network.dat
- osm.pbf.mapdb
- osm.pbf.mapdb.p


 It's important to keep these files in a directory because they can be latter loaded directly (which is super fast) without having to rebuild the network every time. So, in case we decide to go ahead with pointing to separate files, we would need to allow users to indicate the path where the network files above should be saved.

**Comment by HTenkanen** [comment]
@rafapereirabr Good points Rafa! Insights from Matt and Marcus about the internals of R5 and whether pointing separate files for R5 is an issue, would be much appreciated 🙏🏻  

I would be slightly surprised if pointing to a directory instead of specific filepaths would be an issue, but naturally I don't have proper understanding of the R5 internals. Being able to indicate an output path for the graph outputs is a good idea, and I believe there is already a separate issue about the logic for storing the output files in #44.

**Comment by christophfink** [comment]
It is saved automatically, in https://github.com/conveyal/r5/blob/dev/src/main/java/com/conveyal/r5/point_to_point/PointToPointRouterServer.java#L96

**Comment by mvpsaraiva** [comment]
In the very beginning of `r5r` development, we were discussing the possibility of having separate `download_r5()`, `build_network()` and `setup_r5()` functions. But soon we settled for letting `setup_r5()` do all the work transparently (although `download_r5()` still exists internally).

**Comment by christophfink** [comment]
I left the part with handling the caching for R5 out of r5py deliberately, because I was not sure how to avoid the typical caching problems (stale cache files, newer upstream format, ...), and it would have added quite a lot of complexity. At the same time, even for the very detailed network of the Helsinki metropolitan area, parsing the osm.pbf and the gtfs only takes 1min 30s on my normal notebook.

**Comment by christophfink** [comment]
> In the very beginning of `r5r` development, we were discussing the possibility of having separate `download_r5()`, `build_network()` and `setup_r5()` functions. But soon we settled for letting `setup_r5()` do all the work transparently (although `download_r5()` still exists internally).

There is not need to instantiate a separate `TransportNetwork`, the constructor of `TravelTimeMatrix` can take care of it, and of course the functional interface (`r5py.travel_time_matrix(...)`, etc.), can do the same.

**Comment by mvpsaraiva** [comment]
> It is saved automatically, in https://github.com/conveyal/r5/blob/dev/src/main/java/com/conveyal/r5/point_to_point/PointToPointRouterServer.java#L96

Indeed, but we do not use the `PointToPointRouterServer` class in `r5r`, and I didn't know you were using it in `r5py`. Maybe it's a good strategy, but I wouldn't know for sure.

**Comment by christophfink** [comment]
It’s called somewhere under the hood it seems, because even now we end up with cached files in the input directory.

**Comment by mvpsaraiva** [comment]
> There is not need to instantiate a separate `TransportNetwork`, the constructor of `TravelTimeMatrix` can take care of it, and of course the functional interface (`r5py.travel_time_matrix(...)`, etc.), can do the same.

I'm not sure what you mean... we have only one `TransportNetwork` during the entire user session, which is used by everything (`travel_time_matrix()`, `accessibility()`, `detailed_itineraries()` and so on).

**Comment by christophfink** [comment]
But each of them can instantiate a TransportNetwork, if what they are passed as arguments is not a TransportNetwork, but only the parameters for it. (see https://r5py.readthedocs.io/en/stable/reference.html#r5py.TravelTimeMatrix )

So r5py supports the syntax and conventions of r5r, but also allows different pathways.

**Comment by mvpsaraiva** [comment]
> So r5py supports the syntax and conventions of r5r, but also allows different, more pythonic, pathways.

Cool. Perhaps we can change `r5r` a bit to be closer to `r5py`. For example, `setup_r5()` could accept both a path to a data folder or the paths of individual files. But we would have to find a way to deal with the problems this may cause, as in issue #44.
